import type { Dispatch, SetStateAction } from "react";
import { recipeForPreset, recipeWarnings } from "./state";
import type { Recipe } from "./types";

interface RecipeEditorProps { recipe: Recipe; setRecipe: Dispatch<SetStateAction<Recipe>>; }

export function RecipeEditor({ recipe, setRecipe }: RecipeEditorProps) {
  const warnings = recipeWarnings(recipe);
  const changeGeometry = <K extends keyof Recipe["geometry"]>(key: K, value: Recipe["geometry"][K]) => setRecipe((previous) => ({ ...previous, geometry: { ...previous.geometry, [key]: value } }));
  const changeCollision = <K extends keyof Recipe["collision"]>(key: K, value: Recipe["collision"][K]) => setRecipe((previous) => ({ ...previous, collision: { ...previous.collision, [key]: value } }));
  const changeValidation = <K extends keyof Recipe["validation"]>(key: K, value: Recipe["validation"][K]) => setRecipe((previous) => ({ ...previous, validation: { ...previous.validation, [key]: value } }));
  return <section className="panel recipe-panel">
    <div className="panel-heading"><div><p className="eyebrow">Recipe</p><h2>Candidate settings</h2></div><select aria-label="Recipe preset" value={recipe.preset} onChange={(event) => setRecipe((previous) => recipeForPreset(event.target.value as Recipe["preset"], previous))}><option value="close">Close</option><option value="balanced">Balanced</option><option value="distant">Distant</option><option value="collision">Collision</option><option value="custom">Custom</option></select></div>
    <fieldset><legend>Geometry</legend><label className="toggle"><input type="checkbox" checked={recipe.geometry.enabled} onChange={(event) => changeGeometry("enabled", event.target.checked)} /> Simplify candidate mesh</label>
      <div className="form-grid"><label>Strategy<select value={recipe.geometry.strategy} onChange={(event) => changeGeometry("strategy", event.target.value as "target" | "error")}><option value="error">Error ceiling</option><option value="target">Face target</option></select></label><label>{recipe.geometry.strategy === "target" ? "Target faces" : "Maximum error"}<input type="number" min="0" step={recipe.geometry.strategy === "target" ? 100 : 0.0001} value={recipe.geometry.strategy === "target" ? recipe.geometry.target_faces : recipe.geometry.max_error} onChange={(event) => changeGeometry(recipe.geometry.strategy === "target" ? "target_faces" : "max_error", Number(event.target.value))} /></label></div>
      <label className="toggle"><input type="checkbox" checked={recipe.geometry.preserve_boundaries} onChange={(event) => changeGeometry("preserve_boundaries", event.target.checked)} /> Preserve sharp/boundary evidence</label>
      <label className="toggle destructive"><input type="checkbox" checked={recipe.geometry.reconstruct_planar} disabled /> Planar reconstruction (adapter planned)</label>
      <label className="toggle destructive"><input type="checkbox" checked={recipe.geometry.reconstruct_primitives} disabled /> Curved reconstruction (experimental adapter planned)</label>
    </fieldset>
    <fieldset><legend>Collision</legend><label className="toggle"><input type="checkbox" checked={recipe.collision.enabled} onChange={(event) => changeCollision("enabled", event.target.checked)} /> Generate collision</label><div className="form-grid"><label>Representation<select value={recipe.collision.mode} onChange={(event) => changeCollision("mode", event.target.value as Recipe["collision"]["mode"])}>{["auto", "box", "sphere", "cylinder", "capsule", "convex-hull", "compound"].map((option) => <option key={option} value={option}>{option}</option>)}</select></label><label>Fit<select value={recipe.collision.fit} onChange={(event) => changeCollision("fit", event.target.value as Recipe["collision"]["fit"])}>{["cover", "balanced", "inside"].map((option) => <option key={option} value={option}>{option}</option>)}</select></label><label>Use<select value={recipe.collision.body} onChange={(event) => changeCollision("body", event.target.value as Recipe["collision"]["body"])}>{["static", "dynamic", "area"].map((option) => <option key={option} value={option}>{option}</option>)}</select></label></div></fieldset>
    <fieldset><legend>Validation</legend><label className="toggle"><input type="checkbox" checked={recipe.validation.compare_geometry} onChange={(event) => changeValidation("compare_geometry", event.target.checked)} /> Compare geometry</label><label className="toggle"><input type="checkbox" checked={recipe.validation.compare_scene_inventory} onChange={(event) => changeValidation("compare_scene_inventory", event.target.checked)} /> Compare scene inventory</label><label className="toggle"><input type="checkbox" checked={recipe.validation.compare_appearance} onChange={(event) => changeValidation("compare_appearance", event.target.checked)} /> Compare appearance</label></fieldset>
    {warnings.length > 0 && <div className="warning-box">{warnings.map((warning) => <p key={warning}>⚠ {warning}</p>)}</div>}
  </section>;
}
